initial jarvis toolchain

diff --git a/jarvis/Dockerfile b/jarvis/Dockerfile
--- a/jarvis/Dockerfile
+++ b/jarvis/Dockerfile
@@ -3,6 +3,109 @@ FROM gradle:3.5-jdk8
 USER root
 RUN apt-get update && apt-get install bats
 
+################
+RUN useradd -ms /bin/bash elasticsearch
+
+ENV ES_HOME /usr/share/elasticsearch
+
+ENV GOSU_VERSION 1.7
+RUN set -x \
+	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
+	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
+	&& export GNUPGHOME="$(mktemp -d)" \
+	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
+	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
+	&& rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
+	&& chmod +x /usr/local/bin/gosu \
+	&& gosu nobody true
+
+RUN set -ex; \
+# https://artifacts.elastic.co/GPG-KEY-elasticsearch
+	key='46095ACC8548582C1A2699A9D27D666CD88E42B4'; \
+	export GNUPGHOME="$(mktemp -d)"; \
+	gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+	gpg --export "$key" > /etc/apt/trusted.gpg.d/elastic.gpg; \
+	rm -r "$GNUPGHOME"; \
+	apt-key list
+
+# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html
+# https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html
+RUN set -x \
+	&& apt-get update && apt-get install -y --no-install-recommends apt-transport-https && rm -rf /var/lib/apt/lists/* \
+	&& echo 'deb https://artifacts.elastic.co/packages/5.x/apt stable main' > /etc/apt/sources.list.d/elasticsearch.list
+
+ENV ELASTICSEARCH_VERSION 5.3.2
+ENV ELASTICSEARCH_DEB_VERSION 5.3.2
+
+RUN set -x \
+	\
+# don't allow the package to install its sysctl file (causes the install to fail)
+# Failed to write '262144' to '/proc/sys/vm/max_map_count': Read-only file system
+	&& dpkg-divert --rename /usr/lib/sysctl.d/elasticsearch.conf \
+	\
+	&& apt-get update \
+	&& apt-get install -y --no-install-recommends "elasticsearch=$ELASTICSEARCH_DEB_VERSION" \
+	&& rm -rf /var/lib/apt/lists/*
+
+ENV PATH /usr/share/elasticsearch/bin:$PATH
+
+WORKDIR /usr/share/elasticsearch
+
+RUN set -ex \
+	&& for path in \
+		./data \
+		./logs \
+		./config \
+		./config/scripts \
+	; do \
+		mkdir -p "$path"; \
+		chown -R elasticsearch:elasticsearch "$path"; \
+	done
+
+#COPY config ./config
+
+VOLUME /usr/share/elasticsearch/data
+
+WORKDIR $ES_HOME
+RUN mkdir -p config data logs
+
+COPY log4j2.properties /usr/share/elasticsearch/config
+COPY jvm.options /usr/share/elasticsearch/config
+
+COPY elasticsearch.yml config/
+COPY logging.yml config/
+
+COPY elasticsearch.yml /etc/elasticsearch/
+COPY logging.yml /etc/elasticsearch/
+
+
+RUN chown -R elasticsearch: config data logs
+RUN update-rc.d elasticsearch defaults 95 10
+
+
+#################
+
+ENV DEBIAN_FRONTEND noninteractive
+ENV SCALA_VERSION 2.11
+ENV KAFKA_VERSION 0.10.1.0
+ENV KAFKA_HOME /opt/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION"
+
+# Install Kafka, Zookeeper and other needed things
+RUN apt-get update && \
+    apt-get install -y zookeeper wget supervisor dnsutils && \
+    rm -rf /var/lib/apt/lists/* && \
+    apt-get clean && \
+    wget -q http://apache.mirrors.spacedump.net/kafka/"$KAFKA_VERSION"/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz -O /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz && \
+    tar xfz /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz -C /opt && \
+    rm /tmp/kafka_"$SCALA_VERSION"-"$KAFKA_VERSION".tgz
+
+ADD scripts/start-kafka.sh /usr/bin/start-kafka.sh
+
+# Supervisor config
+ADD supervisor/kafka.conf supervisor/zookeeper.conf supervisor/elasticsearch.conf /etc/supervisor/conf.d/
+####
+
+
 ENV SONAR_RUNNER_VERSION 2.4
 ENV SONAR_RUNNER_HOME /opt/sonar-runner-${SONAR_RUNNER_VERSION}
 ENV SONAR_RUNNER_PACKAGE sonar-runner-dist-${SONAR_RUNNER_VERSION}.zip
@@ -14,18 +117,15 @@ RUN wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-di
  && unzip sonar-runner-dist-${SONAR_RUNNER_VERSION}.zip \
  && rm ${SONAR_RUNNER_PACKAGE}
 
-#RUN groupadd -r sonar \
-# && useradd -r -s /usr/sbin/nologin -d ${SONAR_RUNNER_HOME} -c "Sonar service user" -g sonar sonar \
-# && chown -R sonar:sonar ${SONAR_RUNNER_HOME} \
-# && mkdir -p /data \
-# && chown -R sonar:sonar /data
-# USER sonar
-
 WORKDIR /data
 
 VOLUME /data
 RUN echo "" >> ${SONAR_RUNNER_HOME}/conf/sonar-runner.properties
 RUN echo sonar.host.url=http://sonar.qubeship.io >> ${SONAR_RUNNER_HOME}/conf/sonar-runner.properties
+
+
+
+
 
 #ENTRYPOINT ${SONAR_RUNNER_HOME}/bin/sonar-runner
 CMD ["mvn","sonar-runner","bats"]
